---
apiVersion: v1
kind: Namespace
metadata:
  name: cool-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: quarkus-hello
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-hello
  namespace: cool-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-hello
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quarkus-hello
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
      namespace: cool-demo
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ttl.sh/c04768cb-2012-4280-990d-a9adf51c7462:2h
          imagePullPolicy: Always
          name: quarkus-hello
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          workingDir: ./
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: quarkus-hello
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-hello
  namespace: cool-demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-hello
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
